name: flutter_login_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Firebase Core (required)
  firebase_core: ^2.25.0
  
  # Firebase Auth
  firebase_auth: ^4.13.0
  
  # Web-specific dependencies
  firebase_core_web: ^2.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

# Only if you still get the RecaptchaVerifier error
dependency_overrides:
  firebase_auth_web: ^5.9.1