// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeRzm1wNV446lw0BygEfpkXX7gcS1zVDM',
    appId: '1:197605013695:web:d5e400e3597fc94e10ee0a',
    messagingSenderId: '197605013695',
    projectId: 'flutterapp-29de6',
    authDomain: 'flutterapp-29de6.firebaseapp.com',
    storageBucket: 'flutterapp-29de6.firebasestorage.app',
    measurementId: 'G-2E1CYRQ55B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD001UkPjfaQZ3WK9W_2hQmz7K-E2-l2C8',
    appId: '1:197605013695:android:068a0314b2015daf10ee0a',
    messagingSenderId: '197605013695',
    projectId: 'flutterapp-29de6',
    storageBucket: 'flutterapp-29de6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoZT7fGOr_5rThOgjxDshWc87UkHo6bWo',
    appId: '1:197605013695:ios:a29963777a5a53d410ee0a',
    messagingSenderId: '197605013695',
    projectId: 'flutterapp-29de6',
    storageBucket: 'flutterapp-29de6.firebasestorage.app',
    iosBundleId: 'com.example.flutterLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoZT7fGOr_5rThOgjxDshWc87UkHo6bWo',
    appId: '1:197605013695:ios:a29963777a5a53d410ee0a',
    messagingSenderId: '197605013695',
    projectId: 'flutterapp-29de6',
    storageBucket: 'flutterapp-29de6.firebasestorage.app',
    iosBundleId: 'com.example.flutterLoginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeRzm1wNV446lw0BygEfpkXX7gcS1zVDM',
    appId: '1:197605013695:web:989383c90a5d212210ee0a',
    messagingSenderId: '197605013695',
    projectId: 'flutterapp-29de6',
    authDomain: 'flutterapp-29de6.firebaseapp.com',
    storageBucket: 'flutterapp-29de6.firebasestorage.app',
    measurementId: 'G-SWRF20CVMD',
  );
}
